
title: Gerardo Larreinegabe - Resume
url: 'https://alarreine.github.io'
baseurl: '' #change it according to your repository name
exclude: ['README.md', 'LICENCE.md']

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Gerardo Larreinegabe
tagline: Software Engineer
pic: moi.png
summary: With my last degree as a DevOps Engineer and 6 years of experience as a developer working with different languages like 
         Java and Python. I have also experienced administrating and developing database environment like Postgresql and Oracle. 
         I'm working today as a freelance, learning new skills and tools about technologies, automation and the most important, 
         team work. I am interested in sharing and learning knowledge about new ways to build solutions. I wish to continue my career 
         innovating on development projects as a software architect and/or developer/architect.

#sidebar links
email: alarreine@gmail.com
#phone1: +595 981 282 485
#website:
linkedin: agustin-larreinegabe
github: alarreine
#twitter:
style: styles-6

#Update all the sections by editing the files inside _includes folder.

theme: jekyll-theme-cayman
